[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", "uv.lock"]
language-servers = [ "ruff", "pylsp", "pyright" ]
auto-format = true
