#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III
bspc monitor DP-4 -d IV V VI
 
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# load fonts
fc-cache -f -v
sh .config/polybar/launch.sh
feh --bg-scale ~/Pictures/Art/stolas\ in\ a\ tree.png ~/Pictures/Art/miscbits_band_w_bg.PNG

compton --vsync opengl-swc --backend glx
~/.cargo/bin/goxlr/goxlr-daemon &
