#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d IV V VI
bspc monitor DP-4 -d I II III
 
bspc config border_width         0
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# load fonts
fc-cache -f -v
sh ~/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/wallpapers/stolas\ dualtone.png ~/Pictures/Art/miscbits_band_w_bg.PNG

compton --vsync opengl-swc --backend glx &
~/.cargo/bin/goxlr/goxlr-daemon &
